module.exports = {
  apps: [
    {
      name: 'gateway',
      script: './apps/gateway/main.js',
      env: {
        NOTE_SERVICE_PORT:'8001',
        NOTE_SERVICE_HOST:'0.0.0.0',
        TOKEN_SERVICE_PORT:'8002',
        TOKEN_SERVICE_HOST:'0.0.0.0',
        USER_SERVICE_PORT:'8003',
        USER_SERVICE_HOST:'0.0.0.0',
        API_GATEWAY_PORT:'8000',
        BASE_URI:'http://localhost',
        DB_HOST:"localhost",
        DB_PORT:"3306",
        DB_USER:"admin",
        DB_PASS:"admin",
        DB_NAME:"demo",
      }
    },
    {
      name: 'note',
      script: './apps/note/main.js',
      env: {
        NOTE_SERVICE_PORT:'8001',
        NOTE_SERVICE_HOST:'0.0.0.0',
        TOKEN_SERVICE_PORT:'8002',
        TOKEN_SERVICE_HOST:'0.0.0.0',
        USER_SERVICE_PORT:'8003',
        USER_SERVICE_HOST:'0.0.0.0',
        API_GATEWAY_PORT:'8000',
        BASE_URI:'http://localhost',
        DB_HOST:"localhost",
        DB_PORT:"3306",
        DB_USER:"admin",
        DB_PASS:"admin",
        DB_NAME:"demo",
      }
    },
    {
      name: 'token',
      script: './apps/token/main.js',
      env: {
        NOTE_SERVICE_PORT:'8001',
        NOTE_SERVICE_HOST:'0.0.0.0',
        TOKEN_SERVICE_PORT:'8002',
        TOKEN_SERVICE_HOST:'0.0.0.0',
        USER_SERVICE_PORT:'8003',
        USER_SERVICE_HOST:'0.0.0.0',
        API_GATEWAY_PORT:'8000',
        BASE_URI:'http://localhost',
        DB_HOST:"localhost",
        DB_PORT:"3306",
        DB_USER:"admin",
        DB_PASS:"admin",
        DB_NAME:"demo",
      }
    },
    {
      name: 'user',
      script: './apps/user/main.js',
      env: {
        NOTE_SERVICE_PORT:'8001',
        NOTE_SERVICE_HOST:'0.0.0.0',
        TOKEN_SERVICE_PORT:'8002',
        TOKEN_SERVICE_HOST:'0.0.0.0',
        USER_SERVICE_PORT:'8003',
        USER_SERVICE_HOST:'0.0.0.0',
        API_GATEWAY_PORT:'8000',
        BASE_URI:'http://localhost',
        DB_HOST:"localhost",
        DB_PORT:"3306",
        DB_USER:"admin",
        DB_PASS:"admin",
        DB_NAME:"demo",
      }
    },
  ],
};
